buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.6.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://maven.aliyun.com/repository/public'
        }
        maven {
            credentials {
                username '5ff28ca9ed01613630f9d551'
                password 'cxN-HwJ]yzST'
            }
            url 'https://packages.aliyun.com/6718aa5c2c78927f26d82a35/maven/mltcloudai'
        }
    }
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}
